version: '25.0.3'
services:
  chanchito:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - monguito
    volumes:
      - .:/home/app
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=elmer
      - MONGO_INITDB_ROOT_PASSWORD=pocho
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgresql -> /var/lib/postgresql/data
volumes:
  mongo-data:
